# Generated by Django 2.2.7 on 2019-11-04 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Ingrese informacion de la pelicula', max_length=1000)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Autor')),
                ('genre', models.ManyToManyField(to='catalog.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeliculaInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id unico de la pelicula', primary_key=True, serialize=False)),
                ('estreno', models.DateField(blank=True, null=True)),
                ('pelicula_inst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.pelicula')),
            ],
            options={
                'ordering': ['estreno'],
            },
        ),
    ]
