# Generated by Django 2.2.7 on 2019-11-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculainstance',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'SERIES'), ('n', 'NETFLIX'), ('p', 'PELICULAS'), ('e', 'ESTRENOS')], default='e', help_text='Que ver !', max_length=1),
        ),
    ]
