# Generated by Django 2.2.6 on 2019-11-13 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_peliculainstance_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='summary',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='genre',
            new_name='genero',
        ),
        migrations.DeleteModel(
            name='PeliculaInstance',
        ),
    ]
